### ISSUE TITLE
Importing AnywhereLibrary in a test Suite failed

### ISSUE THREAD

**Issue by ghost** [luisxiaomai/robotframework-anywherelibrary#6]
I would like to use this Library to write automated tests on desktop, iOS and Android.
But importing the library fails because this library is using GLOBAL_VARIABLES which is not supported in latest Robotframework versions 2.8.2 and higher...
I am using the latest Robotframework version 3.0

RIDE Error log is as follows:

20170202 11:13:13.126 [WARN]: Importing test library "AnywhereLibrary" failed

Traceback (most recent call last):
Importing test library 'AnywhereLibrary' failed: ImportError: cannot import name GLOBAL_VARIABLES
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 143, in _import
    return __import__(name, fromlist=fromlist)
  File "C:\Python27\lib\site-packages\AnywhereLibrary\__init__.py", line 1, in <module>
    from base import *
  File "C:\Python27\lib\site-packages\AnywhereLibrary\base\__init__.py", line 3, in <module>
    from logging import Logging
  File "C:\Python27\lib\site-packages\AnywhereLibrary\base\logging.py", line 2, in <module>
    from robot.variables import GLOBAL_VARIABLES
PYTHONPATH:
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\Scripts
  C:\Python27\lib\site-packages\robotframework-3.0-py2.7.egg
  C:\Python27\lib\site-packages\decorator-3.3.2-py2.7.egg
  C:\Python27\lib\site-packages\selenium-2.53.2-py2.7.egg
  C:\Windows\system32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\robotide\spec
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 46, in TestLibrary
    return_source=True)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 67, in import_class_or_module
    self._raise_import_failed(name, err)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 103, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by luisxiaomai** [comment]
@m247077, please use master version to install. It fixed this issue.
https://github.com/luisxiaomai/robotframework-anywherelibrary/commit/33594115e05b40ded434c43e3ddb0c7e40de672a
